lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: RS256

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: BEARER
        query_parameter:
            enabled: false
            name: bearer

    remove_token_from_body_when_cookies_used: true

    blocklist_token:
        enabled: true
        cache: cache.app