nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['^https?://(localhost|127\.0\.0\.1|2doitfront-production\.up\.railway\.app)(:[0-9]+)?$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
